/**
 * CV content.
 *
 * Sources, in order of authority:
 *   1. Final_CV_PMRF.tex — your own LaTeX CV (course codes, coursework, grades,
 *      internship detail, full skills, language levels, project write-ups).
 *   2. LinkedIn export — current Poiro role and the dates that fixed the gaps.
 *   3. anandkrishna.me — teaching list and academic service.
 *
 * Where sources disagreed, the LaTeX CV won, as the most recently authored
 * and most detailed of the three.
 *
 * Plain TypeScript rather than a content collection because a CV is one
 * structured document, not a list of pages: you get type-checking and
 * autocomplete while editing, with no loader in the way.
 *
 * After editing anything here, run `npm run cv:pdf` so the PDF matches.
 */

export interface Role {
  role: string;
  org: string;
  orgUrl?: string;
  /** Display strings so you control the formatting: "May 2025", "2018". */
  start: string;
  /** Omit for a current role — renders as "Present". */
  end?: string;
  location?: string;
  summary?: string;
  highlights?: string[];
}

export interface Study {
  qualification: string;
  institution: string;
  start?: string;
  end: string;
  note?: string;
}

export interface Course {
  title: string;
  /** Institution course code, e.g. "E0 230". */
  code?: string;
  /** e.g. "Aug – Dec 2022", or several terms. */
  when: string;
  institution: string;
  role?: 'Teaching Assistant' | 'Instructor';
}

export interface Award {
  title: string;
  date: string;
  awarder?: string;
  url?: string;
}

export interface Language {
  name: string;
  /** Free text: "Native", "Fluent", "Conversational". */
  level: string;
}

export interface CV {
  /** Two or three sentences at the top of the page. */
  summary: string;
  /** Generated by `npm run cv:pdf`; see the note on the value below. */
  resumeUrl?: string;
  experience: Role[];
  education: Study[];
  teaching: Course[];
  awards: Award[];
  /** Venues you've reviewed for. */
  service: string[];
  languages: Language[];
  skills: { group: string; items: string[] }[];
}

export const cv: CV = {
  summary:
    'I lead AI/ML at Poiro, working on generative AI and agentic systems for creative production. Previously a Research Consultant in Walmart’s AdTech team, and a Postdoctoral Research Fellow at the National University of Singapore working on outlier-robust optimization and multi-armed bandits. I completed my Ph.D. at the Indian Institute of Science as a Prime Minister’s Research Fellow, under Prof. Y. Narahari and Assoc. Prof. Siddharth Barman.',

  /**
   * Generated from this very page: `npm run cv:pdf` renders /cv through the
   * print stylesheet into `public/anand-krishna-cv.pdf`, so the PDF and the web
   * CV can never drift. Re-run it after editing anything in this file.
   */
  resumeUrl: '/anand-krishna-cv.pdf',

  experience: [
    {
      role: 'Lead AI Scientist',
      org: 'Poiro',
      orgUrl: 'https://poiro.com',
      start: 'May 2025',
      location: 'Bengaluru, India',
      summary:
        'Leading Data Science & AI. Poiro builds AI systems and agents that supercharge marketing workflows and bring brands closer to consumers.',
      highlights: [
        'AI systems trained on a brand’s structured and unstructured marketing data — social content, marketplace data, first-party customer data — to build a knowledge representation of the brand and its category.',
        'Agents that run analytics and data-science workflows over that representation to produce actionable insight and guide marketing execution.',
        'Used by brands to identify content whitespaces, target creative and creator recommendations at ROI, and audit creator risk before commercial commitments.',
      ],
    },
    {
      role: 'Research Consultant, AdTech',
      org: 'Walmart',
      start: 'Nov 2024',
      end: 'Apr 2025',
      location: 'Bengaluru, India',
      highlights: [
        'Built scalable systems for real-time advertiser query processing to estimate impressions.',
        'Approximate query processing and high-performance data pipelines over large-scale systems.',
      ],
    },
    {
      role: 'Postdoctoral Research Fellow',
      org: 'National University of Singapore',
      orgUrl: 'https://nus.edu.sg/',
      start: 'Sep 2023',
      end: 'Sep 2024',
      location: 'Singapore',
      summary: 'School of Computing, working with Prof. Vincent Y. F. Tan.',
      highlights: [
        'Outlier-robust optimization and multi-armed bandits, including the LEARN invex loss for outlier-oblivious online convex optimization (UAI 2026).',
        'Extended p-mean welfare objectives from social choice to stochastic bandits, unifying average and Nash regret in one algorithm (AAAI 2025).',
        'Sample-efficient alternating minimization for robust phase retrieval, published in IEEE Transactions on Information Theory.',
      ],
    },
    {
      role: 'Prime Minister’s Research Fellow (PMRF)',
      org: 'Indian Institute of Science',
      orgUrl: 'https://iisc.ac.in/',
      start: 'Aug 2018',
      end: 'Aug 2023',
      location: 'Bengaluru, India',
      summary:
        'Ph.D. in the Department of Computer Science and Automation, advised by Prof. Y. Narahari and Assoc. Prof. Siddharth Barman.',
      highlights: [
        'Approximation algorithms for fair division: Nash social welfare and p-mean welfare under subadditive, XOS, and dichotomous valuations.',
        'Results published at ESA 2020, IJCAI 2022, WINE 2022, and ITCS 2024.',
      ],
    },
    {
      role: 'Research Intern',
      org: 'IBM Research India',
      start: 'Jun 2019',
      end: 'Sep 2019',
      location: 'Bengaluru, India',
      highlights: [
        'Developed a privacy-preserving framework for Discrete Preference Games with Dr. Ramasuri Narayanam and Dr. Rishi Saket. Presented the work at IBM and IISc.',
      ],
    },
    {
      role: 'Research and Development Intern',
      org: 'Aindra Systems',
      start: 'Jun 2018',
      end: 'Jul 2018',
      location: 'Bengaluru, India',
      highlights: [
        'Regression models predicting reagent dipping times in the Papanicolaou staining procedure, for Aindra’s auto-stainer.',
      ],
    },
  ],

  education: [
    {
      qualification: 'Direct Ph.D., Intelligent Systems',
      institution: 'Indian Institute of Science',
      start: '2018',
      end: '2023',
      note: 'Department of Computer Science and Automation, as a Prime Minister’s Research Fellow. CGPA 8.9/10. Advised by Prof. Y. Narahari and Assoc. Prof. Siddharth Barman. Coursework included Game Theory, Reinforcement Learning, Linear & Nonlinear Optimization, Stochastic Modeling, Matrix Theory, Foundations of Data Science, and Topics in Pattern Recognition.',
    },
    {
      qualification: 'B.Tech, Computer Science & Engineering',
      institution: 'Government Engineering College, Thrissur',
      start: '2013',
      end: '2017',
      note: 'CGPA 8.28/10.',
    },
  ],

  teaching: [
    {
      title: 'Probability Models',
      when: 'Jan 2021 – Feb 2022',
      institution: 'Dayananda Sagar University',
      role: 'Instructor',
    },
    {
      title: 'Computational Methods of Optimization',
      code: 'E0 230',
      when: 'Aug – Dec 2022',
      institution: 'Indian Institute of Science',
      role: 'Teaching Assistant',
    },
    {
      title: 'Game Theory',
      code: 'E1 254',
      when: 'Jan – Jun 2020, 2021, 2022',
      institution: 'Indian Institute of Science',
      role: 'Teaching Assistant',
    },
    {
      title: 'Randomized Algorithms',
      code: 'E0 234',
      when: 'Feb – Jun 2021',
      institution: 'Indian Institute of Science',
      role: 'Teaching Assistant',
    },
    {
      title: 'Linear Algebra and Probability',
      code: 'E0 226',
      when: 'Aug – Dec 2019',
      institution: 'Indian Institute of Science',
      role: 'Teaching Assistant',
    },
  ],

  awards: [
    {
      title: 'Best Presentation Award, EECS Symposium in Theoretical Computer Science',
      date: 'Mar 2023',
      awarder: 'Indian Institute of Science',
    },
    {
      title:
        'Best Poster Award in Computer Science & Engineering, Data Science and Mathematics — invited to the highlighted poster session',
      date: 'Feb 2023',
      awarder: 'PMRF Symposium, IIT Madras',
    },
    {
      title: 'Invited talk on the IJCAI 2022 paper',
      date: 'Jan 2023',
      awarder: 'National University of Singapore',
    },
    {
      title: 'ADFOCS 2020 summer school on Market Design & Computational Fair Division',
      date: '2020',
      awarder: 'Max Planck Institute for Informatics',
    },
    {
      title: 'Theory of Reinforcement Learning Boot Camp',
      date: '2020',
      awarder: 'Simons Institute for the Theory of Computing',
    },
    {
      title: 'EC’20 Global Outreach Program and EC Mentoring Workshop',
      date: '2020',
      awarder: 'ACM Conference on Economics and Computation',
    },
    {
      title: 'Prime Minister’s Research Fellowship (PMRF)',
      date: '2018',
      awarder: 'Government of India',
    },
  ],

  service: [
    'FOCS 2024',
    'APPROX 2023',
    'WWW 2023',
    'SOSA 2023',
    'WWW 2022',
    'SAGT 2021',
    'WINE 2020',
    'WINE 2019',
  ],

  languages: [
    { name: 'Malayalam', level: 'Native' },
    { name: 'English', level: 'Fluent' },
    { name: 'Tamil', level: 'Conversational' },
    { name: 'Hindi', level: 'Conversational' },
  ],

  skills: [
    {
      group: 'Research areas',
      items: [
        'Game Theory',
        'Fair Division',
        'Online Learning',
        'Randomized Algorithms',
        'Reinforcement Learning',
        'Optimization',
        'Machine Learning',
        'Deep Learning',
        'Statistics',
      ],
    },
    {
      group: 'Programming',
      items: ['Python', 'SQL', 'C++', 'C', 'LaTeX'],
    },
    {
      group: 'Libraries',
      items: ['PyTorch', 'scikit-learn', 'NumPy', 'Pandas', 'PySpark', 'Matplotlib', 'Seaborn'],
    },
  ],
};
